name: Build and Test with TSan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # --- JOB 1: Windows build (no TSan) ---
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Configure CMake (MSVC)
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug .

    - name: Build (MSVC)
      run: cmake --build build --config Debug

    - name: Run executable (MSVC)
      run: ./build/Debug/main.exe --threads 4 --iterations 500000


  # --- JOB 2: Linux build with TSan ---
  build_linux_with_tsan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install GCC (optional, usually pre-installed)
      run: sudo apt-get update && sudo apt-get install -y g++ cmake

    - name: Configure CMake with TSan flags
      run: >
        cmake -B build -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_CXX_FLAGS="-fsanitize=thread -g -O1"
        -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=thread -pthread"
        .

    - name: Build with TSan
      run: cmake --build build

    - name: Run with TSan (expect race detection)
      run: ./build/main ||  true
